### ISSUE TITLE
Ball tracking Issues

### ISSUE THREAD

**Issue by ArthurSalomonIsep** [jac99/FootAndBall#3]
Hi,
I'm a french student interested in doing detection on football match videos and i've come accross your work !

I was just wondering on how can it be used on a real feed of a match (here if i try only the player detection work as the model is trained with SoccerPlayerDetection_bmvc17_v1 dataset to detect player). But the ball is not tracked at all or on a 1/1000 frame (because i guess the model was trained to detect the ball only with ISSIA dataset and this is too precise to adapt the situation to a live feed of a footbal match) 

That's why i wanted to know, to get some advices, on how would it be possible to make it detect the ball on a live feed match (with training i guess) but i'm not sure on how to train it ( don't know about the code needed to read the new dataset )

Thank you !

**Comment by jac99** [comment]
Our pre-trainel model was trained on ISSIA (ball and player) and SoccerPlayerDetection_bmvc17_v1 dataset (only players). If you'd like to detect a ball in videos with different characteristic (e.g. the ball is significantly larger than in ISSIA dataset) you need to train the model or fine-tune it using a different dataset.
The steps you need to accomplish are as follows:
1. You need to prepare a training set, consisting of images with ground truth data on the ball and player position (the ground truth data may be in a text file). The more images the better, but at least few hundreds will be needed.
2. You need to write Dataset class that wraps access to elements of your dataset.
See class IssiaDataset in data/issia_dataset.py or SpdDataset in data/spd_bmvc2017_dataset.py. You need to write a similar class for your dataset.
3. You need to modify make_dataloaders function in data/data_reader.py to create a dataloder object based on your dataset.
4. You need to modify train_detector.py code to train the model using your  dataloader.
There are 2 training strategies that can be considered. One is to train the model from scratch using your new dataset - in such case you need at least few hundreds training images.
The other is to load weights of our model before the training, and then fine-tune the model using your new dataset. In this case fewer training examples are required.
Both scenarios require some knowledge of Pytorch library and general understanding of training deep neural network models.

**Comment by ArthurSalomonIsep** [comment]
Thanks a lot for your answers !

Just a final question I'm wondering if I did right with my videos because i checked and the ball have the same size than in the ISSIA dataset (using 1080p videos with the same size ball) and the ball is not recognized at all am I missing something here ? It will be very cool if it can work without retraining the whole model, can you tell me more about the characteristic the ball need to validate in order to get recognized ? 

Thank you 👍

**Comment by jac99** [comment]
It's difficult to tell what is the reason without deeper investigation. 
You can try to use  the command line argument `--ball_threshold` in `run_detections.py` to decrease the ball detection threshold. Current value is 0.7. This is a threshold on a ball confidence map, the lower it is the more likely the ball will be detected (but you'll have more false detections as well). Set it some low value, e.g. 0.1 and see what happens.
If you want to dig deeper, you need to run a code in a debug mode and inspect ball feature map (ball_feature_map) returned by the trained model on an input image (line 293 in footandball.py). Which locations have the maximum values? Do they correspond to the true ball position? You can visualize the content of this ball feature map and see where maximums are what is the maximum value.

**Comment by AxelGautrand** [comment]
Hi everyone,
Thank you @jac99  for all these usefuls informations about ball tracking. I have managed to reliably track the ball on a game's tv flow by following your advices and by training a new model. If someone is aiming to do the same, I enclose my dataset of 499 annotated frames that I used for this purpose to this message.
I hope this will help you saving annotation time.

Thanks again
[Tiki-Data_annotations_dataset.zip](https://github.com/jac99/FootAndBall/files/5690173/Tiki-Data_annotations_dataset.zip)

**Comment by jac99** [comment]
@AxelGautrand Thanks for sharing the data, and good news our method worked for you. If it's OK for you, I'll make a section "Additional datasets" in the project readme and post your dataset there, so anyone interested can easily find it.

**Comment by AxelGautrand** [comment]
Sure ! Please feel free to do so !

**Comment by srikanth-midde** [comment]
> Hi everyone, Thank you @jac99 for all these usefuls informations about ball tracking and your work on FootAndBall. I have managed to reliably track the ball on a game's tv flow by following your advices and by training a new model. If someone is aiming to do the same, I enclose my dataset of 499 annotated frames that I used for this purpose to this message. I hope this will help you saving annotation time.
> 
> Thanks again [Tiki-Data_annotations_dataset.zip](https://github.com/jac99/FootAndBall/files/5696268/Tiki-Data_annotations_dataset.zip)

**Comment by srikanth-midde** [comment]
Hello AxelGautrand,
I am doing  project on ball tracking in football game. The pre-trained model ISSIA on this Repository is not tracking ball. So I need help to use your dataset in this model.
