### ISSUE TITLE
module 'kornia.feature' has no attribute 'NonMaximaSuppression2d

### ISSUE THREAD

**Issue by srikanth-midde** [jac99/FootAndBall#5]
Hello, 

I am facing the kornia feature "NonMaximaSuppression2d" error in the file /FootAndBall/network/footandball.py, line 161while running this repository. Please help me to sort out this problem

**Comment by KeitelDOG** [comment]
Latest kornia moved the function under `geometry.subpix`. Change:

    self.nms = kornia.feature.NonMaximaSuppression2d(self.nms_kernel_size)

to

    self.nms = kornia.geometry.subpix.NonMaximaSuppression2d(self.nms_kernel_size)

**Comment by srikanth-midde** [comment]
Thanks
